$(document).ready(function(){
    $("#button-setting").click(function(){
        $("#nav-setting-header-0").toggle();
    });
    $("#button-currency").click(function(){
        $("#nav-currency-header-0").toggle();
    });
    $("#button-language").click(function(){
        $("#nav-language-header-0").toggle();
    });
});